### PR TITLE
Function proposal: parseDateTime

### PR DESCRIPTION
**Pull request by leongor**
This PR is related to https://github.com/IBMStreams/streamsx.datetime/issues/13.

### CODE REVIEW

**Comment by leongor** [comment]
The functions parse ISO8601 format and were tested with `fromIso8601ToTimestamp` function for validation.
What is different:
1. The delimiter is not strict - can be any punctuation or whitespace character.
2. Data/time separator can be 'T' or delimiter.
3. Nanoseconds are optional, if present can be any length till 9 characters.
4. TZ is optional, if not present then assumed to be in local TZ.

`updateOffset` parameter is needed only for timestamps in local TZ. To convert it to UTC we need to know the offset including DST. To get it on each function call can have some performance impact. By default, the function get it only once (as a static variable), but if `updateOffset` is set to true, then it will be calculated each time.

**Comment by ddebrunner** [comment]
So it's handling a modified ISO8601, since I don't think ISO8601 allows any identifier does it?

Which other aspects are non-standard for ISO8601?

**Comment by ddebrunner** [comment]
Wouldn't `updateOffset` set to true cause incorrect results when the timezone changes DST while the application is running?

**Comment by ddebrunner** [comment]
Not sure if toolkits are meant to use the version of boost provided by IBM Streams, is that a public api?

**Comment by leongor** [comment]
> So it's handling a modified ISO8601, since I don't think ISO8601 allows any separator does it? Which other aspects are non-standard for ISO8601?

ISO8601 date/time separator is 'T', but here 'T' or delimiter (punct | space) are allowed.

> Wouldn't updateOffset set to true cause incorrect results when the timezone changes DST while the application is running?

Probably you meant updateOffset set to false (meaning it's calculated only once). Yes, in Streams Designer we're using true value (calculated on each call), but the function exposes this parameter because not every country has DST and it has performance impact.

**Comment by ddebrunner** [comment]
So `updateOffset` is really a flag indicating if the local (to Streams instance) timezone has DST or not? Can't we figure that out automatically from the timezone offset? At least the parameter and its doc should represent its logical purpose, not the implementation detail?

So related to that, at somepoint we will need a version that takes a timezeone, as on the Cloud instances the Streams instance timezone most likely will not match what the user wants.

**Comment by leongor** [comment]
Not exactly, `updateOffset` allows to control when calling the function whether the offset should be calculated again (true) or the static value (which calculated on the first call only) can be used (false).
If you think this parameter is confusing we can consider removing it and just getting the offset on each call.

**Comment by leongor** [comment]
After all `updateOffset` parameter is confusing and has no real benefit - removed it.
I've added `missingTimeExc` parameter as one of Streams Designer requirements to have an ability to parse a timestamp without time. By default it's false, but if true then the exception will be thrown.

**Comment by brandtol** [comment]
+1
do you need this change in the upcoming streeams realease ? If so we should merge now.

**Comment by leongor** [comment]
Yes, we do. I'll update the version.

**Comment by brandtol** [comment]
@ddebrunner are you ok with merging this PR ?

**Pull request merged**
